# Generated by Django 6.0.5 on 2026-05-31 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("headquarters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(blank=True, db_column="cargo", max_length=100),
                ),
                (
                    "headquarters",
                    models.ForeignKey(
                        blank=True,
                        db_column="sede_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="administratives",
                        to="headquarters.headquarters",
                    ),
                ),
            ],
            options={
                "verbose_name": "administrativo",
                "verbose_name_plural": "administrativos",
                "db_table": "administrativos",
                "ordering": ["user__apellido", "user__nombre"],
            },
        ),
    ]
