# Generated by Django 6.0.5 on 2026-05-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_column="nombre", max_length=255)),
                (
                    "code",
                    models.CharField(db_column="codigo", max_length=50, unique=True),
                ),
                ("active", models.BooleanField(db_column="activo", default=True)),
            ],
            options={
                "verbose_name": "EPS",
                "verbose_name_plural": "EPS",
                "db_table": "eps",
                "ordering": ["name"],
            },
        ),
    ]
