# Generated by Django 6.0.5 on 2026-06-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eps',
            name='name',
            field=models.CharField(choices=[('SURA', 'Sura'), ('COMPENSAR', 'Compensar'), ('FAMISANAR', 'Famisanar'), ('MEDISALUD', 'Medisalud')], db_column='nombre', max_length=50),
        ),
    ]
