# Generated by Django 6.0.5 on 2026-07-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps', '0002_alter_eps_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eps',
            name='name',
            field=models.CharField(db_column='nombre', max_length=100),
        ),
    ]
