# Generated by Django 6.0.5 on 2026-05-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(db_column="fecha_hora")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(db_column="duracion_minutos"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmada", "Confirmada"),
                            ("cancelada", "Cancelada"),
                            ("reprogramada", "Reprogramada"),
                            ("atendida", "Atendida"),
                        ],
                        db_column="estado",
                        max_length=20,
                    ),
                ),
                (
                    "consultation_reason",
                    models.CharField(
                        blank=True, db_column="motivo_consulta", max_length=255
                    ),
                ),
                ("notes", models.TextField(blank=True, db_column="notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "cita",
                "verbose_name_plural": "citas",
                "db_table": "citas",
                "ordering": ["scheduled_at"],
            },
        ),
    ]
