# Generated by Django 6.0.5 on 2026-05-31 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointment", "0001_initial"),
        ("doctor", "0001_initial"),
        ("headquarters", "0001_initial"),
        ("patient", "0001_initial"),
        ("specialties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="created_by",
            field=models.ForeignKey(
                db_column="creado_por",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                db_column="medico_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="doctor.doctor",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="headquarters",
            field=models.ForeignKey(
                blank=True,
                db_column="sede_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="headquarters.headquarters",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                db_column="paciente_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="patient.patient",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="specialty",
            field=models.ForeignKey(
                db_column="especialidad_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="specialties.specialty",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_minutes__gt", 0)),
                name="appointment_positive_duration",
            ),
        ),
    ]
