# Generated by Django 6.0.5 on 2026-07-07 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_scheduled_at', models.DateTimeField(db_column='fecha_hora_anterior')),
                ('new_scheduled_at', models.DateTimeField(db_column='fecha_hora_nueva')),
                ('reason', models.TextField(blank=True, db_column='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(db_column='cita_id', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='appointment.appointment')),
                ('changed_by', models.ForeignKey(db_column='modificado_por', on_delete=django.db.models.deletion.PROTECT, related_name='appointment_history_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial de cita',
                'verbose_name_plural': 'historial de citas',
                'db_table': 'historial_citas',
                'ordering': ['-created_at'],
            },
        ),
    ]
