# Generated by Django 6.0.5 on 2026-05-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Headquarters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_column="nombre", max_length=150)),
                (
                    "address",
                    models.CharField(blank=True, db_column="direccion", max_length=255),
                ),
                (
                    "phone",
                    models.CharField(blank=True, db_column="telefono", max_length=30),
                ),
                ("active", models.BooleanField(db_column="activo", default=True)),
            ],
            options={
                "verbose_name": "sede",
                "verbose_name_plural": "sedes",
                "db_table": "sedes",
                "ordering": ["name"],
            },
        ),
    ]
