# Generated by Django 6.0.5 on 2026-06-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headquarters',
            name='name',
            field=models.CharField(db_column='nombre', max_length=150, unique=True),
        ),
    ]
