# Generated by Django 6.0.5 on 2026-05-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoctorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        db_column="dia_semana",
                    ),
                ),
                ("start_time", models.TimeField(db_column="hora_inicio")),
                ("end_time", models.TimeField(db_column="hora_fin")),
                (
                    "appointment_duration",
                    models.PositiveIntegerField(db_column="duracion_cita"),
                ),
                ("active", models.BooleanField(db_column="activo", default=True)),
            ],
            options={
                "verbose_name": "disponibilidad médica",
                "verbose_name_plural": "disponibilidades médicas",
                "db_table": "disponibilidad_medico",
                "ordering": ["doctor", "weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_column="fecha")),
                (
                    "reason",
                    models.CharField(blank=True, db_column="motivo", max_length=255),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bloqueo", "Bloqueo"),
                            ("feriado", "Feriado"),
                            ("vacaciones", "Vacaciones"),
                        ],
                        db_column="tipo",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "excepción de horario",
                "verbose_name_plural": "excepciones de horario",
                "db_table": "excepciones_horario",
                "ordering": ["doctor", "date"],
            },
        ),
    ]
