# Generated by Django 6.0.5 on 2026-05-31 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("availability", "0001_initial"),
        ("doctor", "0001_initial"),
        ("headquarters", "0001_initial"),
        ("specialties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctoravailability",
            name="doctor",
            field=models.ForeignKey(
                db_column="medico_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="doctor.doctor",
            ),
        ),
        migrations.AddField(
            model_name="doctoravailability",
            name="headquarters",
            field=models.ForeignKey(
                blank=True,
                db_column="sede_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctor_availabilities",
                to="headquarters.headquarters",
            ),
        ),
        migrations.AddField(
            model_name="doctoravailability",
            name="specialty",
            field=models.ForeignKey(
                db_column="especialidad_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_availabilities",
                to="specialties.specialty",
            ),
        ),
        migrations.AddField(
            model_name="scheduleexception",
            name="doctor",
            field=models.ForeignKey(
                db_column="medico_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_exceptions",
                to="doctor.doctor",
            ),
        ),
        migrations.AddConstraint(
            model_name="doctoravailability",
            constraint=models.CheckConstraint(
                condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)),
                name="doctor_availability_weekday_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="doctoravailability",
            constraint=models.CheckConstraint(
                condition=models.Q(("appointment_duration__gt", 0)),
                name="doctor_availability_positive_duration",
            ),
        ),
    ]
