# Generated by Django 6.0.5 on 2026-06-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='consulting_room',
            field=models.CharField(blank=True, db_column='consultorio', max_length=50),
        ),
    ]
