# Generated by Django 6.0.5 on 2026-05-31 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identity_document",
                    models.CharField(
                        db_column="documento_identidad", max_length=50, unique=True
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CC", "Cédula de ciudadanía"),
                            ("TI", "Tarjeta de identidad"),
                            ("CE", "Cédula de extranjería"),
                            ("PAS", "Pasaporte"),
                        ],
                        db_column="tipo_documento",
                        max_length=3,
                    ),
                ),
                (
                    "date_birth",
                    models.DateField(
                        blank=True, db_column="fecha_nacimiento", null=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, db_column="telefono", max_length=30),
                ),
                (
                    "address",
                    models.CharField(blank=True, db_column="direccion", max_length=255),
                ),
                (
                    "eps",
                    models.ForeignKey(
                        blank=True,
                        db_column="eps_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients",
                        to="eps.eps",
                    ),
                ),
            ],
            options={
                "verbose_name": "paciente",
                "verbose_name_plural": "pacientes",
                "db_table": "pacientes",
                "ordering": ["user__apellido", "user__nombre"],
            },
        ),
    ]
