# Generated by Django 6.0.5 on 2026-06-13 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps', '0002_alter_eps_name'),
        ('patient', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='eps',
            field=models.ForeignKey(db_column='eps_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='eps.eps'),
        ),
    ]
