# Generated by Django 6.0.5 on 2026-06-15 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps', '0002_alter_eps_name'),
        ('patient', '0003_alter_patient_eps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(db_column='direccion', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_birth',
            field=models.DateField(db_column='fecha_nacimiento', default='1990-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='document_type',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('PAS', 'Pasaporte')], db_column='tipo_documento', max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='eps',
            field=models.ForeignKey(db_column='eps_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='eps.eps'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(db_column='telefono', max_length=30),
        ),
    ]
