# Generated by Django 6.0.5 on 2026-06-23 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0002_alter_headquarters_name'),
        ('patient', '0004_alter_patient_address_alter_patient_date_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sede',
            field=models.ForeignKey(blank=True, db_column='sede_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='headquarters.headquarters'),
        ),
    ]
