# Generated by Django 6.0.5 on 2026-07-15 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps', '0003_alter_eps_name'),
        ('patient', '0005_patient_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='eps',
            field=models.ForeignKey(blank=True, db_column='eps_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='eps.eps'),
        ),
    ]
