# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(
                default=0,
                db_column="intentos_fallidos_login",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(
                null=True,
                blank=True,
                db_column="bloqueado_hasta",
            ),
        ),
    ]
