# Generated by Django 6.0.5 on 2026-05-31 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eps", "0001_initial"),
        ("specialties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EPSAppointmentLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("semanal", "Semanal"), ("mensual", "Mensual")],
                        db_column="periodo",
                        max_length=20,
                    ),
                ),
                (
                    "max_appointments",
                    models.PositiveIntegerField(db_column="max_citas"),
                ),
                ("active", models.BooleanField(db_column="activo", default=True)),
                (
                    "eps",
                    models.ForeignKey(
                        db_column="eps_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_limits",
                        to="eps.eps",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        blank=True,
                        db_column="especialidad_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eps_appointment_limits",
                        to="specialties.specialty",
                    ),
                ),
            ],
            options={
                "verbose_name": "tope de citas EPS",
                "verbose_name_plural": "topes de citas EPS",
                "db_table": "topes_citas_eps",
                "ordering": ["eps", "specialty", "period"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("max_appointments__gt", 0)),
                        name="eps_appointment_limit_positive_max",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EPSBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(db_column="periodo_inicio")),
                ("period_end", models.DateField(db_column="periodo_fin")),
                (
                    "total_budget",
                    models.DecimalField(
                        db_column="presupuesto_total", decimal_places=2, max_digits=14
                    ),
                ),
                (
                    "used_budget",
                    models.DecimalField(
                        db_column="presupuesto_usado",
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                    ),
                ),
                (
                    "eps",
                    models.ForeignKey(
                        db_column="eps_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="eps.eps",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        blank=True,
                        db_column="especialidad_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eps_budgets",
                        to="specialties.specialty",
                    ),
                ),
            ],
            options={
                "verbose_name": "presupuesto EPS",
                "verbose_name_plural": "presupuestos EPS",
                "db_table": "presupuesto_eps",
                "ordering": ["eps", "period_start"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("total_budget__gte", 0)),
                        name="eps_budget_non_negative_total",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("used_budget__gte", 0)),
                        name="eps_budget_non_negative_used",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("period_end__gte", models.F("period_start"))
                        ),
                        name="eps_budget_valid_period",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FrequencyRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("semanal", "Semanal"), ("mensual", "Mensual")],
                        db_column="periodo",
                        max_length=20,
                    ),
                ),
                (
                    "max_appointments_per_patient",
                    models.PositiveIntegerField(db_column="max_citas_paciente"),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        blank=True,
                        db_column="especialidad_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequency_restrictions",
                        to="specialties.specialty",
                    ),
                ),
            ],
            options={
                "verbose_name": "restricción de frecuencia",
                "verbose_name_plural": "restricciones de frecuencia",
                "db_table": "restricciones_frecuencia",
                "ordering": ["specialty", "period"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("max_appointments_per_patient__gt", 0)),
                        name="frequency_restriction_positive_max",
                    )
                ],
            },
        ),
    ]
