# Generated by Django 6.0.5 on 2026-07-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps', '0002_alter_eps_name'),
        ('rules', '0001_initial'),
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='epsappointmentlimit',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('eps', 'specialty', 'period'), name='unique_active_eps_limit'),
        ),
    ]
