# Generated by Django 6.0.5 on 2026-05-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identity_document",
                    models.CharField(
                        db_column="documento_identidad", max_length=50, unique=True
                    ),
                ),
                (
                    "register_number",
                    models.CharField(
                        blank=True,
                        db_column="numero_registro",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "academic_information",
                    models.TextField(blank=True, db_column="informacion_academica"),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, db_column="telefono", max_length=30),
                ),
                ("active", models.BooleanField(db_column="activo", default=True)),
            ],
            options={
                "verbose_name": "médico",
                "verbose_name_plural": "médicos",
                "db_table": "medicos",
                "ordering": ["user__apellido", "user__nombre"],
            },
        ),
        migrations.CreateModel(
            name="DoctorSpecialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "especialidad de médico",
                "verbose_name_plural": "especialidades de médicos",
                "db_table": "medico_especialidades",
            },
        ),
    ]
