# Generated by Django 6.0.5 on 2026-05-31 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctor", "0001_initial"),
        ("specialties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                db_column="usuario_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="doctorspecialty",
            name="doctor",
            field=models.ForeignKey(
                db_column="medico_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_specialties",
                to="doctor.doctor",
            ),
        ),
        migrations.AddField(
            model_name="doctorspecialty",
            name="specialty",
            field=models.ForeignKey(
                db_column="especialidad_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_specialties",
                to="specialties.specialty",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="specialties",
            field=models.ManyToManyField(
                related_name="doctors",
                through="doctor.DoctorSpecialty",
                to="specialties.specialty",
            ),
        ),
        migrations.AddConstraint(
            model_name="doctorspecialty",
            constraint=models.UniqueConstraint(
                fields=("doctor", "specialty"), name="unique_doctor_specialty"
            ),
        ),
    ]
