# Generated by Django 6.0.5 on 2026-05-31 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("confirmacion", "Confirmación"),
                            ("recordatorio", "Recordatorio"),
                            ("cancelacion", "Cancelación"),
                            ("alerta_tope", "Alerta de tope"),
                        ],
                        db_column="tipo",
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(db_column="canal", default="email", max_length=30),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("enviada", "Enviada"),
                            ("fallida", "Fallida"),
                        ],
                        db_column="estado",
                        max_length=20,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, db_column="enviada_at", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        db_column="cita_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="appointment.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "notificación",
                "verbose_name_plural": "notificaciones",
                "db_table": "notificaciones",
                "ordering": ["-created_at"],
            },
        ),
    ]
