# Generated by Django 6.0.5 on 2026-07-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('confirmacion', 'Confirmación'), ('recordatorio', 'Recordatorio'), ('cancelacion', 'Cancelación'), ('alerta_tope', 'Alerta de tope'), ('reprogramacion', 'Reprogramación')], db_column='tipo', max_length=20),
        ),
    ]
