# Generated by Django 6.0.5 on 2026-07-15 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
        ('rules', '0002_epsappointmentlimit_unique_active_eps_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='limit',
            field=models.ForeignKey(blank=True, db_column='tope_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='rules.epsappointmentlimit'),
        ),
    ]
