# Generated by Django 6.0.5 on 2026-07-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='error_message',
            field=models.TextField(blank=True, db_column='mensaje_error', null=True),
        ),
    ]
