# Generated by Django 6.0.5 on 2026-07-16 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointmenthistory'),
        ('notifications', '0004_notification_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(blank=True, db_column='cita_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appointment.appointment'),
        ),
    ]
