# Generated by Django 6.0.5 on 2026-07-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_appointment'),
        ('notifications', '0005_notification_error_message'),
    ]

    operations = [
    ]
